version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/setup"
      - "/.github/actions/setup-py"
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 0
    groups:
      js-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/apps/db"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 3
    groups:
      py-dependencies:
        patterns:
          - "*"
