// lines.copy.ts — co-located bilingual copy for the Lines surface (slice-9.3).
//
// The Lines index + the route detail screen own their non-intrinsic, user-facing
// strings here so the .svelte stays markup-only (domain-intrinsic component
// labels — OTP / delay / p90 / severe — already live in the spine's
// ReliabilityPane). FR is the canonical product voice; EN mirrors it.

import { defineCopy, type Locale } from '$lib/i18n/copy';
import type { AffectedAlertsCopy, SurfaceHeadCopy } from '$lib/components/surface';
import { articleCopy } from '$lib/components/layout/articleCopy';
import type { OccupancyCode } from '$lib/v1/schemas';

export const indexCopy = defineCopy({
	fr: {
		kicker: 'LIGNES · RÉSEAU',
		heading: 'Lignes',
		lede: 'Toutes les lignes du réseau, détail du parcours, horaire et fiabilité historique par ligne. Mesuré à partir du contrat /v1.',
		filterLabel: 'Filtrer les lignes',
		filterPlaceholder: 'Numéro ou nom de ligne…',
		controlsLabel: 'Filtres',
		mapAction: 'Carte',
		viewRouteOnMap: (route: string) => `Voir la ligne ${route} sur la carte`,
		more: (n: number) => `+${n} de plus`,
		sortLabel: 'Trier',
		sortAlpha: 'Alphabétique',
		sortWorst: 'Moins fiables',
		statusFilterLabel: 'Fiabilité',
		statusAll: 'Toutes',
		statusProblem: 'En retard',
		statusPending: 'Vérification de la fiabilité des lignes filtrées…',
		rankingPending: 'Calcul du classement de fiabilité des lignes filtrées…',
		modeFilterLabel: 'Mode',
		modeAll: 'Tous les modes',
		routeName: (name: string) => `Nom du parcours · ${name}`,
		directionsNote:
			'Ouvrez une ligne pour voir ensemble toutes les directions et destinations publiées.',
		inventory: {
			label: 'Inventaire du réseau',
			lines: 'Lignes',
			bus: 'Bus',
			metro: 'Métro',
			modes: 'Modes',
			unavailable: 'Indisponible',
		},
	},
	en: {
		kicker: 'LINES · NETWORK',
		heading: 'Lines',
		lede: 'Every line on the network, per-line route detail, schedule and historic reliability. Measured from the /v1 contract.',
		filterLabel: 'Filter lines',
		filterPlaceholder: 'Line number or name…',
		controlsLabel: 'Filters',
		mapAction: 'Map',
		viewRouteOnMap: (route) => `View route ${route} on map`,
		more: (n) => `+${n} more`,
		sortLabel: 'Sort',
		sortAlpha: 'Alphabetical',
		sortWorst: 'Least reliable',
		statusFilterLabel: 'Reliability',
		statusAll: 'All',
		statusProblem: 'Late',
		statusPending: 'Checking reliability for the filtered lines…',
		rankingPending: 'Calculating reliability ranking for the filtered lines…',
		modeFilterLabel: 'Mode',
		modeAll: 'All modes',
		routeName: (name) => `Route name · ${name}`,
		directionsNote: 'Open a line to see every published direction and destination together.',
		inventory: {
			label: 'Network inventory',
			lines: 'Lines',
			bus: 'Bus',
			metro: 'Metro',
			modes: 'Modes',
			unavailable: 'Not available',
		},
	},
}) satisfies Readonly<Record<Locale, SurfaceHeadCopy>>;

export type LinesIndexCopy = (typeof indexCopy)[Locale];

export const detailCopy = defineCopy({
	fr: {
		kicker: 'LIGNE',
		article: articleCopy(
			'fr',
			{
				watermark: 'Ligne',
				provider: 'Source',
				generated: 'Mis à jour',
			},
			{ back: '← Retour aux lignes', tagsAria: 'Mots-clés de la ligne' },
		),
		detailLede:
			'Parcours en direct, horaire prévu et fiabilité historique de cette ligne. Mesuré à partir du contrat /v1.',
		tabs: { detail: 'Détail', schedule: 'Horaire', reliability: 'Fiabilité' },
		profile: {
			title: 'Profil de service',
			summary: 'Structure du parcours et plage de service planifiée.',
			directions: 'Directions',
			stops: 'Arrêts répertoriés',
		},
		liveService: {
			title: 'Service en direct',
			summary: 'Véhicules en service et avis actifs touchant cette ligne.',
		},
		viewOnMap: 'Voir sur la carte',
		viewRouteOnMap: (route: string) => `Voir la ligne ${route} sur la carte`,
		alerts: {
			heading: 'Avis de service',
			listLabel: 'Avis de service touchant cette ligne',
			cause: 'Cause',
			effect: 'Effet',
			from: 'À partir de',
			until: 'Jusqu’à',
			severity: { critical: 'Critique', high: 'Élevé', watch: 'À surveiller' },
			more: (n) => `+${n} de plus`,
			showLess: 'Réduire',
		} satisfies AffectedAlertsCopy,
		directions: 'Directions',
		servicePeriods: 'Périodes de service',
		headways: 'Intervalles',
		scheduleIntro:
			'Les horaires prévus de cette ligne : le premier et le dernier départ, puis l’intervalle prévu entre les bus pour chaque période de la journée. C’est l’offre PLANIFIÉE. Pour la ponctualité réelle, voyez l’onglet « Fiabilité ».',
		scheduleTable: {
			caption: 'Périodes de service planifiées',
			period: 'Période',
			window: 'Plage',
			headway: 'Intervalle prévu',
		},
		weakStops: 'Arrêts les plus faibles',
		direction: (dir: number) => `Direction ${dir}`,
		stopsCount: (n: number) => (n === 1 ? '1 arrêt' : `${n} arrêts`),
		window: 'Plage',
		headway: 'Intervalle',
		firstDeparture: 'Premier départ',
		lastDeparture: 'Dernier départ',
		scheduled: 'Prévu',
		observed: 'Observé',
		excessWait: 'Attente excédentaire',
		regularityCov: 'Régularité (CV)',
		bunched: 'Regroupé',
		avgDelay: 'Retard moyen',
		cancellations: 'Annulations',
		cancellationRate: "Taux d'annulation (30 j)",
		skippedStops: 'Arrêts ignorés',
		skippedStopRate: "Taux d'arrêts ignorés (30 j)",
		crowding: 'Encombrement',
		occupancyBands: {
			empty: 'Vide',
			many_seats: 'Plusieurs places',
			few_seats: 'Peu de places',
			standing: 'Debout',
			full: 'Plein',
		} satisfies Record<OccupancyCode, string>,
		serviceSpan: 'Plage de service',
		spanMinutes: 'Durée (min)',
		firstTripDelay: 'Retard 1er trajet',
		lastTripDelay: 'Retard dernier trajet',
		lastNDays: (n: number) => `sur les ${n} derniers jours`,
		roster: {
			heading: 'Bus en service',
			listLabel: 'Bus en service sur cette ligne',
			busLabel: (id: string) => `Bus ${id}`,
			nextStop: (stop: string) => `Prochain arrêt ${stop}`,
			viewTrip: (id: string) => `Voir le trajet du bus ${id}`,
			viewBusOnMap: (id: string) => `Voir le bus ${id} sur la carte`,
			mapAction: 'Carte',
			count: (n: number) => (n === 1 ? '1 bus en service' : `${n} bus en service`),
			noData: 'Aucune donnée',
		},
		noLiveBus: 'Aucun bus en direct',
		approaching: 'À l’approche',
		viewStop: (stop: string) => `Voir l’arrêt ${stop}`,
		early: (minutes: number) => `${Math.abs(minutes)} min en avance`,
		late: (minutes: number) => `${minutes} min en retard`,
		onTime: "À l'heure",
		noDelay: 'Aucun retard',
		noData: 'sans données',
	},
	en: {
		kicker: 'LINE',
		article: articleCopy(
			'en',
			{
				watermark: 'Line',
				provider: 'Source',
				generated: 'Updated',
			},
			{ back: '← Back to lines', tagsAria: 'Line keywords' },
		),
		detailLede:
			'Live route, planned schedule and historic reliability for this line. Measured from the /v1 contract.',
		tabs: { detail: 'Detail', schedule: 'Schedule', reliability: 'Reliability' },
		profile: {
			title: 'Service profile',
			summary: 'Route structure and planned service span.',
			directions: 'Directions',
			stops: 'Listed stops',
		},
		liveService: {
			title: 'Live service',
			summary: 'Current vehicles and active alerts affecting this line.',
		},
		viewOnMap: 'View on map',
		viewRouteOnMap: (route) => `View route ${route} on map`,
		alerts: {
			heading: 'Service alerts',
			listLabel: 'Service alerts affecting this line',
			cause: 'Cause',
			effect: 'Effect',
			from: 'From',
			until: 'Until',
			severity: { critical: 'Critical', high: 'High', watch: 'Watch' },
			more: (n) => `+${n} more`,
			showLess: 'Show less',
		} satisfies AffectedAlertsCopy,
		directions: 'Directions',
		servicePeriods: 'Service periods',
		headways: 'Headways',
		scheduleIntro:
			'This line’s planned schedule: the first and last departure, then the planned time between buses for each period of the day. This is the PLANNED service. For real-world punctuality, see the “Reliability” tab.',
		scheduleTable: {
			caption: 'Planned service periods',
			period: 'Period',
			window: 'Window',
			headway: 'Planned headway',
		},
		weakStops: 'Weakest stops',
		direction: (dir) => `Direction ${dir}`,
		stopsCount: (n) => (n === 1 ? '1 stop' : `${n} stops`),
		window: 'Window',
		headway: 'Time between buses',
		firstDeparture: 'First departure',
		lastDeparture: 'Last departure',
		scheduled: 'Scheduled',
		observed: 'Observed',
		excessWait: 'Excess wait',
		regularityCov: 'Regularity (CoV)',
		bunched: 'Bunched',
		avgDelay: 'Avg delay',
		cancellations: 'Cancellations',
		cancellationRate: 'Cancellation rate (30d)',
		skippedStops: 'Skipped stops',
		skippedStopRate: 'Skipped-stop rate (30d)',
		crowding: 'Crowding',
		occupancyBands: {
			empty: 'Empty',
			many_seats: 'Many seats',
			few_seats: 'Few seats',
			standing: 'Standing',
			full: 'Full',
		},
		serviceSpan: 'Service span',
		spanMinutes: 'Span (min)',
		firstTripDelay: 'First-trip delay',
		lastTripDelay: 'Last-trip delay',
		lastNDays: (n) => `over the last ${n} days`,
		roster: {
			heading: 'Buses in service',
			listLabel: 'Buses currently running this line',
			busLabel: (id) => `Bus ${id}`,
			nextStop: (stop) => `Next stop ${stop}`,
			viewTrip: (id) => `View the trip for bus ${id}`,
			viewBusOnMap: (id) => `View bus ${id} on map`,
			mapAction: 'Map',
			count: (n) => (n === 1 ? '1 bus in service' : `${n} buses in service`),
			noData: 'No data',
		},
		noLiveBus: 'No live bus',
		approaching: 'Approaching',
		viewStop: (stop) => `View stop ${stop}`,
		early: (minutes) => `${Math.abs(minutes)} min early`,
		late: (minutes) => `${minutes} min late`,
		onTime: 'On time',
		noDelay: 'No delay',
		noData: 'no data',
	},
});

export type RouteDetailCopy = (typeof detailCopy)[Locale];
