table _Measures
	lineageTag: cd3c0245-b5c2-4197-b8a0-60134dad2184

	measure 'Véhicules actifs / Active Vehicles' = ```
			DISTINCTCOUNT(LatestVehicleSnapshot[vehicle_id])
			
			```
		formatString: 0
		lineageTag: 98d4710a-c24b-4b97-87f9-87e008a2b400

	measure 'Trajets en retard / Delayed Trips' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[avg_delay_seconds] > 0))
			
			```
		formatString: 0
		lineageTag: 61639f0a-f565-4117-9b1f-f10fcfe8c69f

	measure 'Trajets en avance / Trips Running Early' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[avg_delay_seconds] < 0))
			
			```
		formatString: 0
		lineageTag: e4ddbb9e-de55-4bc1-a48e-4bed5c7af944

	measure 'Retard moyen sec / Avg Delay Sec' = ```
			AVERAGE(CurrentTripDelayComputed[avg_delay_seconds])
			
			```
		formatString: 0.0
		lineageTag: 450405d1-230c-4dd3-8578-f35b45cb178f

	measure 'Retard moyen 24h / Avg Delay 24h Baseline' = ```
			CALCULATE(
			    AVERAGE(TripDelaySummary5mLive[avg_delay_seconds]),
			    ALL(TripDelaySummary5mLive[period_start_utc])
			)
			
			```
		formatString: 0.0
		lineageTag: 6da046ad-f484-493c-a709-febd5a5d7142

	/// P75 of per-route AVERAGE delay in the current period.
	/// Reads as: "75% of routes had average trip delay no worse than X."
	/// 
	/// History: First tried raw MAX (25-30x avg, blew up the Y-axis with
	/// single ghost-trip spikes). Then P95 over avg_delay — daytime
	/// behaved (200-300s) but overnight spiked to 1000-2500s because
	/// STM's ~70 night routes have higher variance and a few outliers
	/// dominated the small sample.
	/// 
	/// P75 is robust across day AND night service (typical range 40-100s
	/// system-wide, ~1.5x the avg) so the chart stays readable 24h.
	/// Trades absolute "watch the worst routes" signal for stability;
	/// the Routes par état table on row 3 carries the per-route max for
	/// when an operator wants to drill into the absolute worst.
	measure 'Retard P75 (sec) / P75 Delay' = ```
			PERCENTILE.INC(TripDelaySummary5mLive[avg_delay_seconds], 0.75)
			
			```
		formatString: 0
		lineageTag: 960caa79-4af5-4133-88b0-039c20dd83e1

	/// Count of routes whose average trip delay is more than 2x the system
	/// average — a proactive anomaly callout for "routes needing attention
	/// right now". Operator sees the count at a glance; the Routes par état
	/// table on row 3 lets them drill in to find which routes (look for
	/// rows with 'vs moy.' > +100%).
	measure 'Routes hors-normes / Routes Off-Baseline' = ```
			VAR systemAvg =
			    CALCULATE(
			        AVERAGE(CurrentTripDelayComputed[avg_delay_seconds]),
			        ALL(CurrentTripDelayComputed)
			    )
			RETURN COUNTROWS(
			    FILTER(
			        VALUES(CurrentTripDelayComputed[route_id]),
			        CALCULATE(AVERAGE(CurrentTripDelayComputed[avg_delay_seconds]))
			            > systemAvg * 2
			    )
			)
			
			```
		formatString: 0
		lineageTag: 1ce85b02-182a-4b52-99d0-a9954a68024c

	measure 'Écart vs moyenne (%) / Delta vs Avg (%)' = ```
			VAR systemAvg =
			    CALCULATE(
			        AVERAGE(CurrentTripDelayComputed[avg_delay_seconds]),
			        ALL(CurrentTripDelayComputed)
			    )
			VAR routeAvg = AVERAGE(CurrentTripDelayComputed[avg_delay_seconds])
			RETURN DIVIDE(routeAvg - systemAvg, systemAvg)
			
			```
		formatString: +0%;-0%;0%
		lineageTag: 5c35aaa0-6d57-4e95-a780-c6bdf930288f

	/// Same hour yesterday — lights up day 1 (live view has 24h window).
	measure 'Retard 24h hier / Yesterday Same Hour' = ```
			VAR currentHourStart = DATE(YEAR(NOW()), MONTH(NOW()), DAY(NOW())) + TIME(HOUR(NOW()), 0, 0)
			VAR yesterdaySameHourStart = currentHourStart - 1
			VAR yesterdaySameHourEnd = yesterdaySameHourStart + (1/24)
			RETURN CALCULATE(
			    AVERAGE(TripDelaySummary5mLive[avg_delay_seconds]),
			    TripDelaySummary5mLive[period_start_utc] >= yesterdaySameHourStart,
			    TripDelaySummary5mLive[period_start_utc] < yesterdaySameHourEnd
			)
			
			```
		formatString: 0.0
		lineageTag: 5d567dac-3a22-4cdc-b8bb-b522fa8b92eb

	/// 7-day rolling average — partial day 1-6, full from day 7. Sourced from
	/// the batch mart (live view only retains 24h).
	measure 'Retard 7j moyen / 7-day Rolling Avg' = ```
			CALCULATE(
			    AVERAGE(TripDelaySummary5m[avg_delay_seconds]),
			    TripDelaySummary5m[period_start_utc] >= NOW() - 7,
			    TripDelaySummary5m[period_start_utc] <= NOW()
			)
			
			```
		formatString: 0.0
		lineageTag: 7ae12a1d-1512-4227-a286-65589d7ada00

	/// Same hour, exactly 7 days ago — returns BLANK until day 7 of accrual.
	/// Reveals "is today's traffic pattern off-routine vs same time last week."
	measure 'Retard semaine passée même heure / Last Week Same Hour' = ```
			VAR currentHourStart = DATE(YEAR(NOW()), MONTH(NOW()), DAY(NOW())) + TIME(HOUR(NOW()), 0, 0)
			VAR lastWeekSameHourStart = currentHourStart - 7
			VAR lastWeekSameHourEnd = lastWeekSameHourStart + (1/24)
			RETURN CALCULATE(
			    AVERAGE(TripDelaySummary5m[avg_delay_seconds]),
			    TripDelaySummary5m[period_start_utc] >= lastWeekSameHourStart,
			    TripDelaySummary5m[period_start_utc] < lastWeekSameHourEnd
			)
			
			```
		formatString: 0.0
		lineageTag: 7e493639-3291-4b91-88b1-2dce6e344791

	/// Average for the same day-of-week + hour over the last 30 days. Gains
	/// confidence from day 14 (2 samples per DoW); fully reliable from day 30.
	/// Reveals slow-drift trends like "Tuesdays getting worse over a month."
	measure 'Retard 30j même jour de la semaine / Same DoW 30d' = ```
			VAR currentDoW = WEEKDAY(NOW(), 2)
			VAR currentHr = HOUR(NOW())
			RETURN CALCULATE(
			    AVERAGE(TripDelaySummary5m[avg_delay_seconds]),
			    FILTER(
			        TripDelaySummary5m,
			        WEEKDAY(TripDelaySummary5m[period_start_utc], 2) = currentDoW
			            && HOUR(TripDelaySummary5m[period_start_utc]) = currentHr
			            && TripDelaySummary5m[period_start_utc] >= NOW() - 30
			    )
			)
			
			```
		formatString: 0.0
		lineageTag: 39294405-d3c6-4673-bc47-2ac6af3db40b

	/// Z-score: standard deviations from the 7-day mean. |z| > 2 = abnormal.
	/// Returns BLANK until day 7 (needs variance baseline). Powers anomaly
	/// detection once active.
	measure 'Z-score vs moyenne 7j / Z-score vs 7d Avg' = ```
			VAR currentValue = [Retard moyen sec / Avg Delay Sec]
			VAR weeklyMean = [Retard 7j moyen / 7-day Rolling Avg]
			VAR weeklyStdev =
			    CALCULATE(
			        STDEVX.P(
			            VALUES(TripDelaySummary5m[period_start_utc]),
			            CALCULATE(AVERAGE(TripDelaySummary5m[avg_delay_seconds]))
			        ),
			        TripDelaySummary5m[period_start_utc] >= NOW() - 7
			    )
			RETURN DIVIDE(currentValue - weeklyMean, weeklyStdev)
			
			```
		formatString: 0.00
		lineageTag: 7a397c66-7da2-410e-801b-b6ede715611c

	measure 'Retard sévère / Severe Delay' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[max_delay_seconds] > 300))
			
			```
		formatString: 0
		lineageTag: ca489a9f-4e8b-49f4-a75b-1df694444dd7

	measure 'Routes touchées / Affected Routes' = ```
			DISTINCTCOUNT(CurrentTripDelayComputed[route_id])
			
			```
		formatString: 0
		lineageTag: 02fd9c62-37f0-43ce-a92e-d84cb15a61ec

	measure 'Arrêts touchés / Affected Stops' = ```
			DISTINCTCOUNT(FactStopTimeDelayObservation[stop_id])
			
			```
		formatString: 0
		lineageTag: aead665d-ce62-451a-9d93-7ce938a62995

	measure 'Alertes actives / Active Alerts' = ```
			DISTINCTCOUNT(CurrentI3Alerts[alert_id])
			
			```
		formatString: 0
		lineageTag: d51ba51a-2399-4472-a1cc-5321727051e2

	measure 'Âge fraîcheur sec / Freshness Age Sec' = ```
			CALCULATE(
			    MIN(FeedFreshnessCurrent[completed_age_seconds]),
			    FeedFreshnessCurrent[endpoint_key] IN {"trip_updates", "vehicle_positions"}
			)
			
			```
		formatString: 0
		lineageTag: 41372d12-3c78-4870-8a51-7e1ecc27f24e

	measure 'Score impact citoyens / Citizen Impact Score' = ```
			SUM(CitizenAccountabilityDaily[rider_impact_score])
			
			```
		formatString: 0.0
		lineageTag: 85adb108-fd95-4b65-8c7e-0068b48b1312

	measure 'Score habitudes / Habit Score' = ```
			AVERAGE(RouteHabitScore[repeat_problem_score])
			
			```
		formatString: 0.0
		lineageTag: 97ba29f4-7286-44e2-abc3-c6a38617bae0

	measure 'Couleur fraîcheur / Freshness Color' = ```
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(FeedFreshnessCurrent[completed_age_seconds]) <= 30, "#6ECF8F",
			    SELECTEDVALUE(FeedFreshnessCurrent[completed_age_seconds]) <= 60, "#FFB627",
			    "#E07800"
			)
			
			```
		lineageTag: 498326fe-1cfd-429c-9d4d-d9dff1859891

	measure 'Couleur retard / Delay Color' = ```
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(CurrentTripDelayComputed[max_delay_seconds]) <= 60, "#6ECF8F",
			    SELECTEDVALUE(CurrentTripDelayComputed[max_delay_seconds]) <= 300, "#FFB627",
			    "#E07800"
			)
			
			```
		lineageTag: 8995a3cb-39f8-41e4-9e75-4df6aee2875b

	column Column1
		dataType: string
		isHidden
		lineageTag: 9d137bb5-dd0c-42fd-80d1-12b149ca1a5c
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows({{"_Measures"}}, type table [Column1 = text])
				in
				    Source

	annotation PBI_ResultType = Table

