table _Measures

	measure 'Véhicules actifs / Active Vehicles' = ```
			DISTINCTCOUNT(LatestVehicleSnapshot[vehicle_id])
			
			```
		formatString: 0

	measure 'Trajets en retard / Delayed Trips' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[avg_delay_seconds] > 0))
			
			```
		formatString: 0

	measure 'Retard moyen sec / Avg Delay Sec' = ```
			AVERAGE(CurrentTripDelayComputed[avg_delay_seconds])
			
			```
		formatString: 0.0

	measure 'Retard sévère / Severe Delay' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[max_delay_seconds] > 300))
			
			```
		formatString: 0

	measure 'Routes touchées / Affected Routes' = ```
			DISTINCTCOUNT(CurrentTripDelayComputed[route_id])
			
			```
		formatString: 0

	measure 'Arrêts touchés / Affected Stops' = ```
			DISTINCTCOUNT(FactStopTimeDelayObservation[stop_id])
			
			```
		formatString: 0

	measure 'Alertes actives / Active Alerts' = ```
			DISTINCTCOUNT(CurrentI3Alerts[alert_id])
			
			```
		formatString: 0

	measure 'Âge fraîcheur sec / Freshness Age Sec' = ```
			CALCULATE(
			    MIN(FeedFreshnessCurrent[completed_age_seconds]),
			    FeedFreshnessCurrent[endpoint_key] IN {"trip_updates", "vehicle_positions"}
			)
			
			```
		formatString: 0

	measure 'Score impact citoyens / Citizen Impact Score' = ```
			SUM(CitizenAccountabilityDaily[rider_impact_score])
			
			```
		formatString: 0.0

	measure 'Score habitudes / Habit Score' = ```
			AVERAGE(RouteHabitScore[repeat_problem_score])

			```
		formatString: 0.0

	measure 'Couleur fraîcheur / Freshness Color' = ```
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(FeedFreshnessCurrent[completed_age_seconds]) <= 30, "#6ECF8F",
			    SELECTEDVALUE(FeedFreshnessCurrent[completed_age_seconds]) <= 60, "#FFB627",
			    "#E07800"
			)

			```

	measure 'Couleur retard / Delay Color' = ```
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(CurrentTripDelayComputed[max_delay_seconds]) <= 60, "#6ECF8F",
			    SELECTEDVALUE(CurrentTripDelayComputed[max_delay_seconds]) <= 300, "#FFB627",
			    "#E07800"
			)

			```

	column Column1
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows({{"_Measures"}}, type table [Column1 = text])
				in
				    Source

	annotation PBI_ResultType = Table
