table _Measures

	measure 'Véhicules actifs / Active Vehicles' = ```
			DISTINCTCOUNT(LatestVehicleSnapshot[vehicle_id])
			
			```
		formatString: 0

	measure 'Trajets en retard / Delayed Trips' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[avg_delay_seconds] > 0))

			```
		formatString: 0

	measure 'Trajets en avance / Trips Running Early' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[avg_delay_seconds] < 0))

			```
		formatString: 0

	measure 'Retard moyen sec / Avg Delay Sec' = ```
			AVERAGE(CurrentTripDelayComputed[avg_delay_seconds])

			```
		formatString: 0.0

	measure 'Retard moyen 24h / Avg Delay 24h Baseline' = ```
			CALCULATE(
			    AVERAGE(TripDelaySummary5mLive[avg_delay_seconds]),
			    ALL(TripDelaySummary5mLive[period_start_utc])
			)

			```
		formatString: 0.0

	/// P75 of per-route AVERAGE delay in the current period.
	/// Reads as: "75% of routes had average trip delay no worse than X."
	///
	/// History: First tried raw MAX (25-30x avg, blew up the Y-axis with
	/// single ghost-trip spikes). Then P95 over avg_delay — daytime
	/// behaved (200-300s) but overnight spiked to 1000-2500s because
	/// STM's ~70 night routes have higher variance and a few outliers
	/// dominated the small sample.
	///
	/// P75 is robust across day AND night service (typical range 40-100s
	/// system-wide, ~1.5x the avg) so the chart stays readable 24h.
	/// Trades absolute "watch the worst routes" signal for stability;
	/// the Routes par état table on row 3 carries the per-route max for
	/// when an operator wants to drill into the absolute worst.
	measure 'Retard P75 (sec) / P75 Delay' = ```
			PERCENTILE.INC(TripDelaySummary5mLive[avg_delay_seconds], 0.75)

			```
		formatString: 0

	/// Count of routes whose average trip delay is more than 2x the system
	/// average — a proactive anomaly callout for "routes needing attention
	/// right now". Operator sees the count at a glance; the Routes par état
	/// table on row 3 lets them drill in to find which routes (look for
	/// rows with 'vs moy.' > +100%).
	measure 'Routes hors-normes / Routes Off-Baseline' = ```
			VAR systemAvg =
			    CALCULATE(
			        AVERAGE(CurrentTripDelayComputed[avg_delay_seconds]),
			        ALL(CurrentTripDelayComputed)
			    )
			RETURN COUNTROWS(
			    FILTER(
			        VALUES(CurrentTripDelayComputed[route_id]),
			        CALCULATE(AVERAGE(CurrentTripDelayComputed[avg_delay_seconds]))
			            > systemAvg * 2
			    )
			)

			```
		formatString: 0

	measure 'Écart vs moyenne (%) / Delta vs Avg (%)' = ```
			VAR systemAvg =
			    CALCULATE(
			        AVERAGE(CurrentTripDelayComputed[avg_delay_seconds]),
			        ALL(CurrentTripDelayComputed)
			    )
			VAR routeAvg = AVERAGE(CurrentTripDelayComputed[avg_delay_seconds])
			RETURN DIVIDE(routeAvg - systemAvg, systemAvg)

			```
		formatString: +0%;-0%;0%

	/// Same hour yesterday — lights up day 1 (live view has 24h window).
	measure 'Retard 24h hier / Yesterday Same Hour' = ```
			VAR currentHourStart = DATE(YEAR(NOW()), MONTH(NOW()), DAY(NOW())) + TIME(HOUR(NOW()), 0, 0)
			VAR yesterdaySameHourStart = currentHourStart - 1
			VAR yesterdaySameHourEnd = yesterdaySameHourStart + (1/24)
			RETURN CALCULATE(
			    AVERAGE(TripDelaySummary5mLive[avg_delay_seconds]),
			    TripDelaySummary5mLive[period_start_utc] >= yesterdaySameHourStart,
			    TripDelaySummary5mLive[period_start_utc] < yesterdaySameHourEnd
			)

			```
		formatString: 0.0

	/// 7-day rolling average — partial day 1-6, full from day 7. Sourced from
	/// the batch mart (live view only retains 24h).
	measure 'Retard 7j moyen / 7-day Rolling Avg' = ```
			CALCULATE(
			    AVERAGE(TripDelaySummary5m[avg_delay_seconds]),
			    TripDelaySummary5m[period_start_utc] >= NOW() - 7,
			    TripDelaySummary5m[period_start_utc] <= NOW()
			)

			```
		formatString: 0.0

	/// Same hour, exactly 7 days ago — returns BLANK until day 7 of accrual.
	/// Reveals "is today's traffic pattern off-routine vs same time last week."
	measure 'Retard semaine passée même heure / Last Week Same Hour' = ```
			VAR currentHourStart = DATE(YEAR(NOW()), MONTH(NOW()), DAY(NOW())) + TIME(HOUR(NOW()), 0, 0)
			VAR lastWeekSameHourStart = currentHourStart - 7
			VAR lastWeekSameHourEnd = lastWeekSameHourStart + (1/24)
			RETURN CALCULATE(
			    AVERAGE(TripDelaySummary5m[avg_delay_seconds]),
			    TripDelaySummary5m[period_start_utc] >= lastWeekSameHourStart,
			    TripDelaySummary5m[period_start_utc] < lastWeekSameHourEnd
			)

			```
		formatString: 0.0

	/// Average for the same day-of-week + hour over the last 30 days. Gains
	/// confidence from day 14 (2 samples per DoW); fully reliable from day 30.
	/// Reveals slow-drift trends like "Tuesdays getting worse over a month."
	measure 'Retard 30j même jour de la semaine / Same DoW 30d' = ```
			VAR currentDoW = WEEKDAY(NOW(), 2)
			VAR currentHr = HOUR(NOW())
			RETURN CALCULATE(
			    AVERAGE(TripDelaySummary5m[avg_delay_seconds]),
			    FILTER(
			        TripDelaySummary5m,
			        WEEKDAY(TripDelaySummary5m[period_start_utc], 2) = currentDoW
			            && HOUR(TripDelaySummary5m[period_start_utc]) = currentHr
			            && TripDelaySummary5m[period_start_utc] >= NOW() - 30
			    )
			)

			```
		formatString: 0.0

	/// Z-score: standard deviations from the 7-day mean. |z| > 2 = abnormal.
	/// Returns BLANK until day 7 (needs variance baseline). Powers anomaly
	/// detection once active.
	measure 'Z-score vs moyenne 7j / Z-score vs 7d Avg' = ```
			VAR currentValue = [Retard moyen sec / Avg Delay Sec]
			VAR weeklyMean = [Retard 7j moyen / 7-day Rolling Avg]
			VAR weeklyStdev =
			    CALCULATE(
			        STDEVX.P(
			            VALUES(TripDelaySummary5m[period_start_utc]),
			            CALCULATE(AVERAGE(TripDelaySummary5m[avg_delay_seconds]))
			        ),
			        TripDelaySummary5m[period_start_utc] >= NOW() - 7
			    )
			RETURN DIVIDE(currentValue - weeklyMean, weeklyStdev)

			```
		formatString: 0.00

	measure 'Retard sévère / Severe Delay' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[max_delay_seconds] > 300))
			
			```
		formatString: 0

	measure 'Routes touchées / Affected Routes' = ```
			DISTINCTCOUNT(CurrentTripDelayComputed[route_id])
			
			```
		formatString: 0

	measure 'Arrêts touchés / Affected Stops' = ```
			DISTINCTCOUNT(FactStopTimeDelayObservation[stop_id])
			
			```
		formatString: 0

	measure 'Alertes actives / Active Alerts' = ```
			DISTINCTCOUNT(CurrentI3Alerts[alert_id])
			
			```
		formatString: 0

	measure 'Âge fraîcheur sec / Freshness Age Sec' = ```
			CALCULATE(
			    MIN(FeedFreshnessCurrent[completed_age_seconds]),
			    FeedFreshnessCurrent[endpoint_key] IN {"trip_updates", "vehicle_positions"}
			)
			
			```
		formatString: 0

	measure 'Score impact citoyens / Citizen Impact Score' = ```
			SUM(CitizenAccountabilityDaily[rider_impact_score])
			
			```
		formatString: 0.0

	measure 'Score habitudes / Habit Score' = ```
			AVERAGE(RouteHabitScore[repeat_problem_score])

			```
		formatString: 0.0

	measure 'Couleur fraîcheur / Freshness Color' = ```
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(FeedFreshnessCurrent[completed_age_seconds]) <= 30, "#6ECF8F",
			    SELECTEDVALUE(FeedFreshnessCurrent[completed_age_seconds]) <= 60, "#FFB627",
			    "#E07800"
			)

			```

	measure 'Couleur retard / Delay Color' = ```
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(CurrentTripDelayComputed[max_delay_seconds]) <= 60, "#6ECF8F",
			    SELECTEDVALUE(CurrentTripDelayComputed[max_delay_seconds]) <= 300, "#FFB627",
			    "#E07800"
			)

			```

	column Column1
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows({{"_Measures"}}, type table [Column1 = text])
				in
				    Source

	annotation PBI_ResultType = Table
