table _Measures

	measure 'Véhicules actifs / Active Vehicles' = ```
			DISTINCTCOUNT(LatestVehicleSnapshot[vehicle_id])
			
			```
		formatString: 0

	measure 'Trajets en retard / Delayed Trips' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[avg_delay_seconds] > 0))
			
			```
		formatString: 0

	measure 'Retard moyen sec / Avg Delay Sec' = ```
			AVERAGE(CurrentTripDelayComputed[avg_delay_seconds])
			
			```
		formatString: 0.0

	measure 'Retard sévère / Severe Delay' = ```
			COUNTROWS(FILTER(CurrentTripDelayComputed, CurrentTripDelayComputed[max_delay_seconds] > 300))
			
			```
		formatString: 0

	measure 'Routes touchées / Affected Routes' = ```
			DISTINCTCOUNT(CurrentTripDelayComputed[route_id])
			
			```
		formatString: 0

	measure 'Arrêts touchés / Affected Stops' = ```
			DISTINCTCOUNT(FactStopTimeDelayObservation[stop_id])
			
			```
		formatString: 0

	measure 'Alertes actives / Active Alerts' = ```
			DISTINCTCOUNT(CurrentI3Alerts[alert_id])
			
			```
		formatString: 0

	measure 'Âge fraîcheur sec / Freshness Age Sec' = ```
			MAX(FeedFreshnessCurrent[completed_age_seconds])
			
			```
		formatString: 0

	measure 'Score impact citoyens / Citizen Impact Score' = ```
			SUM(CitizenAccountabilityDaily[rider_impact_score])
			
			```
		formatString: 0.0

	measure 'Score habitudes / Habit Score' = ```
			AVERAGE(RouteHabitScore[repeat_problem_score])
			
			```
		formatString: 0.0

	column Column1
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows({{}}, type table [Column1 = text])
				in
				    Source

	annotation PBI_ResultType = Table
