// Co-located copy for the live map hero (Family A, slice-9.3).
//
// Surface-level prose only. The StatusCode / OccupancyCode display labels now live
// beside the enums they render, in the shared $lib/v1/enumLabels vocabulary (S7.5
// P3), so the map legend and the network band never drift again.

import { defineCopy, type Locale } from '$lib/i18n/copy';

export const copy = defineCopy({
	en: {
		kicker: 'NETWORK · LIVE',
		heading: 'Live map',
		mapLabel: 'Live transit map of Montréal, buses coloured by status',
		detailPanelLabel: 'Selection details',
		detailResizeLabel: 'Resize details panel',
		modeStatus: 'Status',
		modeOccupancy: 'Crowding',
		modeAlerts: 'Alerts',
		modeRoutes: 'Routes',
		modeStops: 'Stops',
		modeVehicles: 'Buses',
		modeTrips: 'Trips',
		modeAria: 'Colour buses by',
		nearMe: 'Stops near me',
		nearMeUseLocation: 'Use my location',
		nearMeSearchPlaceholder: 'Address, postal code, or coordinates',
		nearMeSearchSubmit: 'Find',
		nearMeClear: 'Clear location',
		nearMeLoading: 'Finding stops...',
		nearMeNoResults: 'No nearby stops',
		nearMeError: 'Could not find that place',
		nearMeGeoDenied: 'Location permission denied',
		nearMeGeoTimeout: 'Location timed out. Try again',
		nearMeGeoUnavailable: 'Location unavailable',
		nearMeGeoInsecure: 'Location needs a secure (https) connection',
		noData: 'No data',
		entityBus: 'Bus',
		entityStop: 'Stop',
		legendTitle: 'Markers',
		entityFilterTitle: 'Filter map markers',
		filterTitle: 'Filter',
		controlsTitle: 'Controls',
		filterClear: 'Clear',
		filterClose: 'Close filters',
		routeRemove: 'Remove route',
		vehicleLabel: 'Bus',
		stopLabel: 'Stop',
		tripLabel: 'Trip',
		vehicleRemove: 'Remove bus',
		stopRemove: 'Remove stop',
		tripRemove: 'Remove trip',
		alertHas: 'Has alert',
		alertHasAria: 'Show markers with alerts',
		liveUnavailable: 'Live data unavailable right now. The map and stops still work.',
		liveNoVehicles: 'No vehicles to show right now.',
		feedNotResponding: (age) => `Live feed not responding. Last update ${age}.`,
		motion: {
			label: 'Motion',
			smooth: 'Almost real-time',
			raw: 'Raw',
			toRaw: 'Switch to raw positions (measured only, no estimation)',
			toSmooth: 'Switch to almost real-time (estimated motion between reports)',
			hintSmooth: 'Estimated motion between reports',
			hintRaw: 'Measured positions only',
			explain: 'How this works',
		},
	},
	fr: {
		kicker: 'RÉSEAU · EN DIRECT',
		heading: 'Carte en direct',
		mapLabel: 'Carte en direct du réseau de Montréal, bus colorés par statut',
		detailPanelLabel: 'Détails de la sélection',
		detailResizeLabel: 'Redimensionner le panneau de détails',
		modeStatus: 'Statut',
		modeOccupancy: 'Achalandage',
		modeAlerts: 'Alertes',
		modeRoutes: 'Lignes',
		modeStops: 'Arrêts',
		modeVehicles: 'Bus',
		modeTrips: 'Trajets',
		modeAria: 'Colorer les bus par',
		nearMe: 'Arrêts près de moi',
		nearMeUseLocation: 'Utiliser ma position',
		nearMeSearchPlaceholder: 'Adresse, code postal ou coordonnées',
		nearMeSearchSubmit: 'Trouver',
		nearMeClear: 'Effacer le lieu',
		nearMeLoading: 'Recherche des arrêts...',
		nearMeNoResults: 'Aucun arrêt proche',
		nearMeError: 'Lieu introuvable',
		nearMeGeoDenied: 'Autorisation de localisation refusée',
		nearMeGeoTimeout: 'Délai de localisation dépassé. Réessayez',
		nearMeGeoUnavailable: 'Localisation indisponible',
		nearMeGeoInsecure: 'La localisation requiert une connexion sécurisée (https)',
		noData: 'Aucune donnée',
		entityBus: 'Bus',
		entityStop: 'Arrêt',
		legendTitle: 'Marqueurs',
		entityFilterTitle: 'Filtrer les marqueurs de la carte',
		filterTitle: 'Filtrer',
		controlsTitle: 'Contrôles',
		filterClear: 'Effacer',
		filterClose: 'Fermer les filtres',
		routeRemove: 'Retirer la ligne',
		vehicleLabel: 'Bus',
		stopLabel: 'Arrêt',
		tripLabel: 'Trajet',
		vehicleRemove: 'Retirer le bus',
		stopRemove: "Retirer l'arrêt",
		tripRemove: 'Retirer le trajet',
		alertHas: 'Avec alerte',
		alertHasAria: 'Afficher les marqueurs avec alertes',
		liveUnavailable:
			'Données en direct indisponibles pour l’instant. La carte et les arrêts fonctionnent toujours.',
		liveNoVehicles: 'Aucun véhicule à afficher pour l’instant.',
		feedNotResponding: (age: string) =>
			`Le flux en direct ne répond pas. Dernière mise à jour ${age}.`,
		motion: {
			label: 'Mouvement',
			smooth: 'Presque en temps réel',
			raw: 'Brut',
			toRaw: 'Passer aux positions brutes (mesurées seulement, sans estimation)',
			toSmooth: 'Passer au presque en temps réel (mouvement estimé entre les relevés)',
			hintSmooth: 'Mouvement estimé entre les relevés',
			hintRaw: 'Positions mesurées seulement',
			explain: 'Comment ça marche',
		},
	},
});

export type MapCopy = (typeof copy)[Locale];
