import { defineCopy, type Locale } from '$lib/i18n/copy';

export const copy = defineCopy({
	en: {
		staticKicker: '{city} · STATIC',
		staticHeading: '{city} transit map',
		staticBody:
			'Static, non-live basemap. No vehicles, stops, service alerts, or freshness data are shown.',
		bootHeading: 'Live map · {city}',
		bootBody:
			'The live interactive map loads automatically. This static basemap stays visible until it is ready.',
		staticUnavailable: 'Basemap preview unavailable for {city}. The live map loads automatically.',
		staticSnapshot: 'Basemap data · {date}',
		staticImageAlt: 'Static basemap · {city}',
		mapBooting: 'Loading live map · {city}…',
		mapImportError: 'Live map could not start · {city}.',
		mapImportRetry: 'Try live map again',
		staticNoScript: 'JavaScript is required to load the live interactive map.',
		kicker: 'NETWORK · LIVE',
		heading: 'Network map',
		mapLabel: '{city} network map with vehicle status',
		mapCanvasLabel: 'Interactive map',
		attributionToggle: 'Toggle attribution',
		mapErrorTitle: 'Map unavailable',
		mapErrorBody: 'The map could not start. Try again.',
		mapRetry: 'Retry map',
		detailPanelLabel: 'Selection details',
		detailResizeLabel: 'Resize details panel',
		modeStatus: 'Status',
		modeOccupancy: 'Crowding',
		modeAlerts: 'Alerts',
		modeRoutes: 'Routes',
		modeStops: 'Stops',
		modeVehicles: 'Vehicles',
		modeTrips: 'Trips',
		modeAria: 'Colour vehicles by',
		nearMe: 'Stops near me',
		nearMeUseLocation: 'Use my location',
		nearMeSearchPlaceholder: 'Address, postal code, or coordinates',
		nearMeSearchSubmit: 'Find',
		nearMeCollectionNotice:
			'Your searches are sent to our server and the Government of Canada Geo.ca service.',
		nearMeClear: 'Clear location',
		nearMeLoading: 'Finding stops...',
		nearMeNoResults: 'No nearby stops',
		nearMeError: 'Could not find that place',
		nearMeGeoDenied: 'Location permission denied',
		nearMeGeoTimeout: 'Location timed out. Try again',
		nearMeGeoUnavailable: 'Location unavailable',
		nearMeGeoInsecure: 'Location needs a secure (https) connection',
		entityBus: 'Vehicle',
		entityStop: 'Stop',
		legendTitle: 'Markers',
		entityFilterTitle: 'Filter map markers',
		filterTitle: 'Filter',
		controlsTitle: 'Controls',
		activeTitle: 'Active',
		controlsCollapse: 'Collapse controls',
		controlsExpand: 'Expand controls',
		controlsDone: 'Done',
		rail: {
			motion: 'Pos.',
			markers: 'Mark.',
			alerts: 'Alerts',
			active: 'Active',
			status: 'Status',
			crowding: 'Crowd',
		},
		filterClear: 'Clear',
		filterClose: 'Close filters',
		routeRemove: 'Remove route',
		vehicleLabel: 'Vehicle',
		stopLabel: 'Stop',
		tripLabel: 'Trip',
		vehicleRemove: 'Remove vehicle',
		stopRemove: 'Remove stop',
		tripRemove: 'Remove trip',
		alertHas: 'Has alert',
		alertFilterUnavailable: 'Filter unavailable: no alert feed connected.',
		alertHasAria: 'Show markers with alerts',
		latestReport: 'Latest report',
		liveUnavailable: 'Live vehicle positions unavailable right now. The map and stops still work.',
		liveNoVehicles: 'No vehicles to show right now.',
		familyVehicles: 'vehicle positions',
		familyTrips: 'trip details',
		familyDepartures: 'departures',
		familyAlerts: 'service alerts',
		selectedFamilyFailure: (family: string, retained: boolean) =>
			retained
				? `Live data for ${family} is unavailable. Showing the last successful update.`
				: `Live data for ${family} is unavailable right now.`,
		feedNotResponding: (age) => `Live feed not responding. Last update ${age}.`,
		feedNotRespondingShort: 'not responding',
		motion: {
			label: 'Positions',
			smooth: 'Estimated',
			raw: 'Reported',
			toRaw: 'Show reported positions only',
			toSmooth: 'Animate estimated positions between reports',
			hintSmooth: 'Between reports',
			hintRaw: 'Latest reports',
			explain: 'Method',
		},
	},
	fr: {
		staticKicker: '{city} · STATIQUE',
		staticHeading: 'Carte du réseau · {city}',
		staticBody:
			'Fond de carte statique, pas en direct. Aucun véhicule, arrêt, avis de service ou renseignement de fraîcheur n’est affiché.',
		bootHeading: 'Carte en direct · {city}',
		bootBody:
			'La carte interactive en direct se charge automatiquement. Ce fond de carte statique reste visible jusqu’à ce qu’elle soit prête.',
		staticUnavailable:
			'Aperçu cartographique indisponible · {city}. La carte en direct se charge automatiquement.',
		staticSnapshot: 'Données cartographiques · {date}',
		staticImageAlt: 'Fond de carte statique · {city}',
		mapBooting: 'Chargement de la carte en direct · {city}…',
		mapImportError: 'La carte en direct n’a pas pu démarrer · {city}.',
		mapImportRetry: 'Réessayer la carte en direct',
		staticNoScript: 'JavaScript est requis pour charger la carte interactive en direct.',
		kicker: 'RÉSEAU · EN DIRECT',
		heading: 'Carte du réseau',
		mapLabel: 'Carte du réseau · {city}, avec l’état des véhicules',
		mapCanvasLabel: 'Carte interactive',
		attributionToggle: 'Afficher ou masquer les attributions',
		mapErrorTitle: 'Carte indisponible',
		mapErrorBody: 'La carte n’a pas pu démarrer. Réessayez.',
		mapRetry: 'Réessayer la carte',
		detailPanelLabel: 'Détails de la sélection',
		detailResizeLabel: 'Redimensionner le panneau de détails',
		modeStatus: 'Statut',
		modeOccupancy: 'Achalandage',
		modeAlerts: 'Alertes',
		modeRoutes: 'Lignes',
		modeStops: 'Arrêts',
		modeVehicles: 'Véhicules',
		modeTrips: 'Trajets',
		modeAria: 'Colorer les véhicules par',
		nearMe: 'Arrêts près de moi',
		nearMeUseLocation: 'Utiliser ma position',
		nearMeSearchPlaceholder: 'Adresse, code postal ou coordonnées',
		nearMeSearchSubmit: 'Trouver',
		nearMeCollectionNotice:
			'Vos recherches sont envoyées à notre serveur et au service Géo.ca du gouvernement du Canada.',
		nearMeClear: 'Effacer le lieu',
		nearMeLoading: 'Recherche des arrêts...',
		nearMeNoResults: 'Aucun arrêt proche',
		nearMeError: 'Lieu introuvable',
		nearMeGeoDenied: 'Autorisation de localisation refusée',
		nearMeGeoTimeout: 'Délai de localisation dépassé. Réessayez',
		nearMeGeoUnavailable: 'Localisation indisponible',
		nearMeGeoInsecure: 'La localisation requiert une connexion sécurisée (https)',
		entityBus: 'Véhicule',
		entityStop: 'Arrêt',
		legendTitle: 'Marqueurs',
		entityFilterTitle: 'Filtrer les marqueurs de la carte',
		filterTitle: 'Filtrer',
		controlsTitle: 'Contrôles',
		activeTitle: 'Actifs',
		controlsCollapse: 'Réduire les contrôles',
		controlsExpand: 'Développer les contrôles',
		controlsDone: 'Terminé',
		rail: {
			motion: 'Pos.',
			markers: 'Marq.',
			alerts: 'Alertes',
			active: 'Actifs',
			status: 'Statut',
			crowding: 'Achal.',
		},
		filterClear: 'Effacer',
		filterClose: 'Fermer les filtres',
		routeRemove: 'Retirer la ligne',
		vehicleLabel: 'Véhicule',
		stopLabel: 'Arrêt',
		tripLabel: 'Trajet',
		vehicleRemove: 'Retirer le véhicule',
		stopRemove: "Retirer l'arrêt",
		tripRemove: 'Retirer le trajet',
		alertHas: 'Avec alerte',
		alertFilterUnavailable: 'Filtre indisponible : aucune source d’alertes connectée.',
		alertHasAria: 'Afficher les marqueurs avec alertes',
		latestReport: 'Dernier rapport',
		liveUnavailable:
			'Positions des véhicules en direct indisponibles pour l’instant. La carte et les arrêts fonctionnent toujours.',
		liveNoVehicles: 'Aucun véhicule à afficher pour l’instant.',
		familyVehicles: 'les positions des véhicules',
		familyTrips: 'les détails des trajets',
		familyDepartures: 'les départs',
		familyAlerts: 'les alertes de service',
		selectedFamilyFailure: (family: string, retained: boolean) =>
			retained
				? `Les données en direct pour ${family} sont indisponibles. La dernière mise à jour réussie reste affichée.`
				: `Les données en direct pour ${family} sont indisponibles pour l’instant.`,
		feedNotResponding: (age: string) =>
			`Le flux en direct ne répond pas. Dernière mise à jour ${age}.`,
		feedNotRespondingShort: 'ne répond pas',
		motion: {
			label: 'Positions',
			smooth: 'Estimées',
			raw: 'Signalées',
			toRaw: 'Afficher les positions signalées seulement',
			toSmooth: 'Animer les positions estimées entre les relevés',
			hintSmooth: 'Entre les relevés',
			hintRaw: 'Derniers signalements',
			explain: 'Méthode',
		},
	},
});

export type MapCopy = (typeof copy)[Locale];

export function mapCopy(locale: Locale, city: string): MapCopy {
	return Object.fromEntries(
		Object.entries(copy[locale]).map(([key, value]) => [
			key,
			typeof value === 'string' ? value.replaceAll('{city}', city) : value,
		]),
	) as MapCopy;
}
