// Co-located copy for the map selection-detail panel (the right-overlay / mobile
// sheet body). Bilingual vocabulary as DATA, lifted out of MapSelectionDetail.svelte
// so the component is markup + wiring only (logic/copy separation). Some entries are
// count/age formatters, so the shape is inferred via `as const` rather than a hand-
// written interface.

import type { Locale } from '$lib/i18n';

export const MAP_SELECTION_DETAIL_COPY = {
	en: {
		bus: 'Bus',
		stop: 'Stop',
		route: 'Route',
		trip: 'Trip',
		status: 'Status',
		crowding: 'Crowding',
		delay: 'Delay',
		nextStop: 'Next stop',
		stopCode: 'Stop code',
		alerts: 'Alerts',
		cause: 'Cause',
		effect: 'Effect',
		noAlerts: 'No alerts attached',
		noData: 'No data',
		early: (minutes: number) => `${Math.abs(minutes)} min early`,
		late: (minutes: number) => `${minutes} min late`,
		onTime: 'On time',
		departures: (count: number) => `${count} departure${count === 1 ? '' : 's'}`,
		vehiclesHeading: (count: number) => `${count} bus${count === 1 ? '' : 'es'} heading here`,
		visibleBuses: (count: number) => `${count} bus${count === 1 ? '' : 'es'} visible`,
		direction: 'Direction',
		routes: 'Routes',
		stops: 'Stops',
		pastStops: 'Past stops',
		nextStops: 'Next stops',
		pastTimes: 'Past times',
		nextTimes: 'Next times',
		live: 'Live',
		selectRoute: (route: string) => `Select route ${route}`,
		selectDepartureRoute: (route: string) => `Select departure route ${route}`,
		selectStop: (stop: string) => `Select stop ${stop}`,
		selectBus: (bus: string) => `Select bus ${bus}`,
		selectAlert: (alert: string) => `Select alert ${alert}`,
		filterStatus: (status: string) => `Filter status ${status}`,
		filterCrowding: (crowding: string) => `Filter crowding ${crowding}`,
		filterTrip: (trip: string) => `Filter trip ${trip}`,
		liveBuses: 'Live buses',
		notReporting: 'Not reporting GPS',
		lastPosition: (age: string) => `last updated position ${age} ago`,
	},
	fr: {
		bus: 'Bus',
		stop: 'Arrêt',
		route: 'Ligne',
		trip: 'Trajet',
		status: 'Statut',
		crowding: 'Achalandage',
		delay: 'Retard',
		nextStop: 'Prochain arrêt',
		stopCode: "Code d'arrêt",
		alerts: 'Alertes',
		cause: 'Cause',
		effect: 'Effet',
		noAlerts: 'Aucune alerte liée',
		noData: 'Aucune donnée',
		early: (minutes: number) => `${Math.abs(minutes)} min en avance`,
		late: (minutes: number) => `${minutes} min en retard`,
		onTime: "À l'heure",
		departures: (count: number) => `${count} départ${count === 1 ? '' : 's'}`,
		vehiclesHeading: (count: number) => `${count} bus vers cet arrêt`,
		visibleBuses: (count: number) => `${count} bus visible${count === 1 ? '' : 's'}`,
		direction: 'Direction',
		routes: 'Lignes',
		stops: 'Arrêts',
		pastStops: 'Arrêts passés',
		nextStops: 'Prochains arrêts',
		pastTimes: 'Passages passés',
		nextTimes: 'Prochains passages',
		live: 'Direct',
		selectRoute: (route: string) => `Sélectionner la ligne ${route}`,
		selectDepartureRoute: (route: string) => `Sélectionner le départ de la ligne ${route}`,
		selectStop: (stop: string) => `Sélectionner l’arrêt ${stop}`,
		selectBus: (bus: string) => `Sélectionner le bus ${bus}`,
		selectAlert: (alert: string) => `Sélectionner l’alerte ${alert}`,
		filterStatus: (status: string) => `Filtrer le statut ${status}`,
		filterCrowding: (crowding: string) => `Filtrer l’achalandage ${crowding}`,
		filterTrip: (trip: string) => `Filtrer le trajet ${trip}`,
		liveBuses: 'Bus en direct',
		notReporting: 'Pas de signal GPS',
		lastPosition: (age: string) => `dernière position il y a ${age}`,
	},
} as const;

/** The selection-detail copy for one locale (the shape both locales share). */
export type MapSelectionDetailCopy = (typeof MAP_SELECTION_DETAIL_COPY)[Locale];
