"""Historic-tier builders (Phase 3) — gold reliability rollups -> /v1/historic.

OTP convention: otp_pct = round(100 * on_time / known), NULL if either side is
unknown or known==0 — every published rounding is half-away-from-zero (Postgres
ROUND parity; 2026-07-01 rebaseline), owned by ``gold.reader.rates``.
Stop reliability keeps a documented severe-delay proxy,
now over real per-stop delay observations rather than route-smeared values.
avg_delay_min = round(avg_delay_seconds/60, 1); severe_pct = round(100*sev/known, 1).
p50_min/p90_min for route/stop reliability come from an append-only daily
percentile rollup (route: per local day; stop: most recent closed day); weekly
and monthly grains stay None because percentiles are not additively composable.

This package was split from a single ``historic.py`` module (S7-close C3) into
per-surface leaves over a shared spine kernel (``_spine``) — a pure mechanical
refactor, byte-identical SQL and math (proven by a seeded before/after payload
byte-comparison). The dependency graph is acyclic: ``__init__ -> {network_trend,
route_reliability, stop_reliability, small_surfaces, provenance} -> _spine ->
{gold.reader, _helpers, contract}``; ``_helpers -> gold.reader`` (no arrow ever
points from gold.reader into snapshots).

This facade re-exports every module-level SQL constant, private helper, and
``build_*`` name the pre-split ``historic.py`` exposed, so all
``builders.historic.<name>`` import + attribute paths (publish.py's attribute
access, the tests' from-imports and ``historic.<attr>`` reads) stay byte-stable
with zero importer edits.
"""

from __future__ import annotations

# Re-exported for parity with the pre-split module surface (imported from
# _helpers by static.py; the old module re-exported it as
# builders.historic._ROUTE_SCHEDULE_SQL). Kept so the attribute path never
# disappears.
from transit_ops.snapshots.builders._helpers import (
    _ROUTE_NAMES_SQL,  # noqa: F401 - re-exported for attribute-path parity
    _ROUTE_SCHEDULE_SQL,  # noqa: F401 - re-exported for attribute-path parity
    _STOP_NAMES_SQL,  # noqa: F401 - re-exported for attribute-path parity
)

# --- shared spine kernel (value helpers, projector fold catalog, spine +
#     windowed consumer helpers, headway / weak-stop kernels) ---
from transit_ops.snapshots.builders.historic._spine import (
    _GAP_EDGES,
    _GAP_HIST_COLS,
    _GAP_NBINS,
    _HEADWAY_SHIFT_ANCHOR_SQL,
    _HEADWAY_WINDOW_SQL,
    _MIN_N_HABIT_CELL,
    _MIN_N_WEAK_STOP,
    _NETWORK_SPINE_BY_DAYTYPE_SQL,
    _NETWORK_SPINE_BY_SHIFT_SQL,
    _OCCUPANCY_BANDS,
    _ROUTE_HABIT_SPINE_SQL,
    _ROUTE_SPINE_BY_DAYTYPE_SQL,
    _ROUTE_SPINE_BY_SHIFT_SQL,
    _ROUTE_SPINE_CROSSTAB_SQL,
    _ROUTE_SPINE_DOW_SQL,
    _ROUTE_SPINE_MONTHLY_SQL,
    _ROUTE_SPINE_WEEKLY_SQL,
    _SPINE_ANCHOR_SQL,
    _SPINE_DAYTYPE_CASE,
    _SPINE_SHIFT_CASE,
    _STOP_DELAY_ANCHOR_SQL,
    _STOP_WEAK_WINDOW_SQL,
    _W_BY_DAYTYPE,
    _W_BY_SHIFT,
    _W_CROSSTAB,
    _W_DOW,
    _WEAK_STOPS_BY_GRAIN_CAP,
    _attach_prior,
    _band_total,
    _bunched_pct_from_hist,
    _delay_by_crowding_cells,
    _grain_windows,
    _headway_by_grain,
    _headway_pctile_from_hist,
    _headway_period_from_summed,
    _headway_shift_anchor,
    _network_spine_rows,
    _occupancy_mix_from_bands,
    _pctile_from_hist,
    _round_half_away,
    _route_spine_sql,
    _shift_key,
    _spine_anchor,
    _spine_delay_histogram,
    _spine_habits_by_grain,
    _spine_hist_and_avg,
    _spine_periods_by_grain,
    _spine_project_sql,
    _spine_reliability_period,
    _spine_route_crosstab,
    _spine_route_dow,
    _spine_route_periods,
    _stop_delay_anchor,
    _weak_stops_by_grain,
    _windowed_otp_index,
    _windowed_periods,
)
from transit_ops.snapshots.builders.historic.alert_archive import (
    _ALERT_ARCHIVE_SQL,
    AlertArchiveBundle,
    build_alert_archive,
)
from transit_ops.snapshots.builders.historic.line_history import (
    LINE_HISTORY_ENTITY_BATCH_SIZE,
    LINE_HISTORY_METRICS,
    LineHistoryBundle,
    LineHistoryPlan,
    LineHistoryStreamSummary,
    build_line_history,
    build_line_history_from_rows,
    build_line_history_plan,
    build_line_history_plan_from_rows,
)
from transit_ops.snapshots.builders.historic.network_history import (
    _NETWORK_HISTORY_CANCELLATION_SQL,
    _NETWORK_HISTORY_DELAY_SQL,
    _NETWORK_HISTORY_FACT_SQL,
    _NETWORK_HISTORY_OCCUPANCY_SQL,
    NetworkHistoryBundle,
    NetworkHistoryPlan,
    build_network_history,
    build_network_history_from_rows,
    build_network_history_plan,
    build_network_history_plan_from_rows,
)
from transit_ops.snapshots.builders.historic.network_trend import (
    _NETWORK_DAYTYPE_ORDER,
    _NETWORK_SHIFT_ORDER,
    _TREND_CANCELLATION_MONTHLY_SQL,
    _TREND_CANCELLATION_SQL,
    _TREND_CANCELLATION_WEEKLY_SQL,
    _TREND_DAILY_SQL,
    _TREND_FACT_SQL,
    _TREND_MONTHLY_SQL,
    _TREND_OCCUPANCY_MONTHLY_SQL,
    _TREND_OCCUPANCY_SQL,
    _TREND_OCCUPANCY_WEEKLY_SQL,
    _TREND_WEEKLY_SQL,
    _blank_trend_point,
    _trend_points,
    build_network_trend,
)
from transit_ops.snapshots.builders.historic.provenance import (
    _PROVENANCE_CONFORMANCE_SQL,
    _PROVENANCE_FRESHNESS_SQL,
    _PROVENANCE_SOURCES_SQL,
    _PROVIDER_GAPS,
    _build_provenance_conformance,
    build_provenance,
)
from transit_ops.snapshots.builders.historic.route_reliability import (
    _ROUTE_CANCELLATION_DAILY_SQL,
    _ROUTE_CROWDING_DELAY_SQL,
    _ROUTE_HEADWAY_DIRECTION_SQL,
    _ROUTE_HEADWAY_OBSERVED_SQL,
    _ROUTE_OCCUPANCY_BAND_WINDOW_SQL,
    _ROUTE_OCCUPANCY_BY_DOW_SQL,
    _ROUTE_OCCUPANCY_BY_GRAIN_SQL,
    _ROUTE_PERCENTILE_DAILY_SQL,
    _ROUTE_REL_DAILY_SQL,
    _ROUTE_SERVICE_SPAN_SQL,
    _ROUTE_SKIPPED_STOP_SQL,
    _ROUTE_WEAK_STOPS_SQL,
    _route_cancellations,
    _route_headway,
    _route_occupancy,
    _route_periods,
    _route_service_spans,
    _route_skipped_stops,
    _route_weak_stops,
    build_route_reliability,
)
from transit_ops.snapshots.builders.historic.small_surfaces import (
    _ALERT_HISTORY_SQL,
    _HOTSPOTS_ROUTE_SHIFT_SQL,
    _HOTSPOTS_ROUTE_WINDOW_SQL,
    _HOTSPOTS_SQL,
    _HOTSPOTS_STOP_SHIFT_SQL,
    _HOTSPOTS_STOP_WINDOW_SQL,
    _RECEIPTS_ACCOUNTABILITY_SQL,
    _RECEIPTS_NETWORK_DAILY_SQL,
    _RECEIPTS_NOT_REPORTED_ROUTES_SQL,
    _RECEIPTS_SERVICE_STATES_SQL,
    _RECEIPTS_SHIFT_DAILY_SQL,
    _RECEIPTS_WORST_ROUTE_SQL,
    _RECEIPTS_WORST_STOP_SQL,
    _REPEAT_OFFENDERS_SQL,
    _SENTINEL_ENTITY_IDS,
    _alert_breakdown,
    _hotspots_by_grain,
    _otp_delta_pts,
    build_alert_history,
    build_hotspots,
    build_receipts,
    build_repeat_offenders,
)
from transit_ops.snapshots.builders.historic.stop_reliability import (
    _STOP_BY_GRAIN_SQL,
    _STOP_DOW_SQL,
    _STOP_HABIT_SQL,
    _STOP_OCCUPANCY_BAND_WINDOW_SQL,
    _STOP_PERCENTILE_DAILY_SQL,
    _STOP_REL_ANCHOR_SQL,
    _STOP_REL_BY_ROUTE_SQL,
    _STOP_REL_MONTHLY_SQL,
    _STOP_REL_WEEKLY_SQL,
    build_stop_reliability,
)

__all__ = [
    # builders
    "build_network_trend",
    "build_network_history",
    "build_network_history_from_rows",
    "build_network_history_plan",
    "build_network_history_plan_from_rows",
    "build_line_history",
    "build_line_history_from_rows",
    "build_line_history_plan",
    "build_line_history_plan_from_rows",
    "build_provenance",
    "build_route_reliability",
    "build_alert_history",
    "build_alert_archive",
    "build_hotspots",
    "build_receipts",
    "build_repeat_offenders",
    "build_stop_reliability",
    "AlertArchiveBundle",
    "NetworkHistoryBundle",
    "NetworkHistoryPlan",
    "LineHistoryBundle",
    "LineHistoryPlan",
    "LineHistoryStreamSummary",
    "LINE_HISTORY_ENTITY_BATCH_SIZE",
    "LINE_HISTORY_METRICS",
    "_ALERT_ARCHIVE_SQL",
    # SQL constants + private helpers re-exported for byte-stable
    # builders.historic.<name> attribute + import-path parity
    "_GAP_EDGES",
    "_GAP_HIST_COLS",
    "_GAP_NBINS",
    "_HEADWAY_SHIFT_ANCHOR_SQL",
    "_HEADWAY_WINDOW_SQL",
    "_MIN_N_HABIT_CELL",
    "_MIN_N_WEAK_STOP",
    "_NETWORK_SPINE_BY_DAYTYPE_SQL",
    "_NETWORK_SPINE_BY_SHIFT_SQL",
    "_OCCUPANCY_BANDS",
    "_ROUTE_HABIT_SPINE_SQL",
    "_ROUTE_SPINE_BY_DAYTYPE_SQL",
    "_ROUTE_SPINE_BY_SHIFT_SQL",
    "_ROUTE_SPINE_CROSSTAB_SQL",
    "_ROUTE_SPINE_DOW_SQL",
    "_ROUTE_SPINE_MONTHLY_SQL",
    "_ROUTE_SPINE_WEEKLY_SQL",
    "_SPINE_ANCHOR_SQL",
    "_SPINE_DAYTYPE_CASE",
    "_SPINE_SHIFT_CASE",
    "_STOP_DELAY_ANCHOR_SQL",
    "_STOP_WEAK_WINDOW_SQL",
    "_WEAK_STOPS_BY_GRAIN_CAP",
    "_W_BY_DAYTYPE",
    "_W_BY_SHIFT",
    "_W_CROSSTAB",
    "_W_DOW",
    "_attach_prior",
    "_band_total",
    "_bunched_pct_from_hist",
    "_delay_by_crowding_cells",
    "_grain_windows",
    "_headway_by_grain",
    "_headway_pctile_from_hist",
    "_headway_period_from_summed",
    "_headway_shift_anchor",
    "_network_spine_rows",
    "_occupancy_mix_from_bands",
    "_pctile_from_hist",
    "_round_half_away",
    "_route_spine_sql",
    "_shift_key",
    "_spine_anchor",
    "_spine_delay_histogram",
    "_spine_habits_by_grain",
    "_spine_hist_and_avg",
    "_spine_periods_by_grain",
    "_spine_project_sql",
    "_spine_reliability_period",
    "_spine_route_crosstab",
    "_spine_route_dow",
    "_spine_route_periods",
    "_stop_delay_anchor",
    "_weak_stops_by_grain",
    "_windowed_otp_index",
    "_windowed_periods",
    "_NETWORK_HISTORY_CANCELLATION_SQL",
    "_NETWORK_HISTORY_DELAY_SQL",
    "_NETWORK_HISTORY_FACT_SQL",
    "_NETWORK_HISTORY_OCCUPANCY_SQL",
    "_NETWORK_DAYTYPE_ORDER",
    "_NETWORK_SHIFT_ORDER",
    "_TREND_CANCELLATION_MONTHLY_SQL",
    "_TREND_CANCELLATION_SQL",
    "_TREND_CANCELLATION_WEEKLY_SQL",
    "_TREND_DAILY_SQL",
    "_TREND_FACT_SQL",
    "_TREND_MONTHLY_SQL",
    "_TREND_OCCUPANCY_MONTHLY_SQL",
    "_TREND_OCCUPANCY_SQL",
    "_TREND_OCCUPANCY_WEEKLY_SQL",
    "_TREND_WEEKLY_SQL",
    "_blank_trend_point",
    "_trend_points",
    "_PROVENANCE_CONFORMANCE_SQL",
    "_PROVENANCE_FRESHNESS_SQL",
    "_PROVENANCE_SOURCES_SQL",
    "_PROVIDER_GAPS",
    "_build_provenance_conformance",
    "_ROUTE_CANCELLATION_DAILY_SQL",
    "_ROUTE_CROWDING_DELAY_SQL",
    "_ROUTE_HEADWAY_DIRECTION_SQL",
    "_ROUTE_HEADWAY_OBSERVED_SQL",
    "_ROUTE_OCCUPANCY_BAND_WINDOW_SQL",
    "_ROUTE_OCCUPANCY_BY_DOW_SQL",
    "_ROUTE_OCCUPANCY_BY_GRAIN_SQL",
    "_ROUTE_PERCENTILE_DAILY_SQL",
    "_ROUTE_REL_DAILY_SQL",
    "_ROUTE_SERVICE_SPAN_SQL",
    "_ROUTE_SKIPPED_STOP_SQL",
    "_ROUTE_WEAK_STOPS_SQL",
    "_route_cancellations",
    "_route_headway",
    "_route_occupancy",
    "_route_periods",
    "_route_service_spans",
    "_route_skipped_stops",
    "_route_weak_stops",
    "_ALERT_HISTORY_SQL",
    "_HOTSPOTS_SQL",
    "_HOTSPOTS_ROUTE_WINDOW_SQL",
    "_HOTSPOTS_STOP_WINDOW_SQL",
    "_HOTSPOTS_ROUTE_SHIFT_SQL",
    "_HOTSPOTS_STOP_SHIFT_SQL",
    "_RECEIPTS_ACCOUNTABILITY_SQL",
    "_RECEIPTS_NETWORK_DAILY_SQL",
    "_RECEIPTS_NOT_REPORTED_ROUTES_SQL",
    "_RECEIPTS_SERVICE_STATES_SQL",
    "_RECEIPTS_SHIFT_DAILY_SQL",
    "_RECEIPTS_WORST_ROUTE_SQL",
    "_RECEIPTS_WORST_STOP_SQL",
    "_REPEAT_OFFENDERS_SQL",
    "_SENTINEL_ENTITY_IDS",
    "_alert_breakdown",
    "_hotspots_by_grain",
    "_otp_delta_pts",
    "_STOP_BY_GRAIN_SQL",
    "_STOP_DOW_SQL",
    "_STOP_HABIT_SQL",
    "_STOP_OCCUPANCY_BAND_WINDOW_SQL",
    "_STOP_PERCENTILE_DAILY_SQL",
    "_STOP_REL_ANCHOR_SQL",
    "_STOP_REL_BY_ROUTE_SQL",
    "_STOP_REL_MONTHLY_SQL",
    "_STOP_REL_WEEKLY_SQL",
    "_ROUTE_NAMES_SQL",
    "_ROUTE_SCHEDULE_SQL",
    "_STOP_NAMES_SQL",
]
