// stops.copy.ts — co-located bilingual copy for the Stops surface (slice-9.3).
//
// All user-facing strings the StopsIndex + StopDetail screens render live here,
// keyed by Locale, so the .svelte files carry zero inline copy. Domain-intrinsic
// labels (OTP / delay / "LIVE" / tab vocabulary inside the spine primitives)
// already live in those primitives and are NOT duplicated here.

import { defineCopy, type Locale } from '$lib/i18n/copy';
import type { AffectedAlertsCopy, SurfaceHeadCopy } from '$lib/components/surface';

export const indexCopy = defineCopy({
	fr: {
		kicker: 'ARRÊTS · CATALOGUE',
		heading: 'Arrêts',
		subheading: '// RECHERCHE',
		lede: 'Cherchez un arrêt par nom ou par code pour voir ses prochains passages et sa fiabilité. On n’invente jamais de données.',
		searchPlaceholder: 'Nom ou code d’arrêt…',
		searchLabel: 'Rechercher un arrêt',
		noMatches: 'Aucun arrêt ne correspond à cette recherche.',
		more: (n: number) => `+${n} autres arrêts, affinez la recherche`,
		mapAction: 'Carte',
		viewStopOnMap: (stop: string) => `Voir l’arrêt ${stop} sur la carte`,
		controlsLabel: 'Filtres',
		lineLabel: 'Filtrer par ligne',
		linePlaceholder: 'Numéro ou nom de ligne…',
		lineClear: 'Effacer le filtre de ligne',
		lineEmpty: 'Aucune ligne ne correspond.',
		onLineHeading: (short: string) => `Arrêts de la ligne ${short}`,
		noLineStops: 'Aucune liste d’arrêts publiée pour cette ligne.',
		direction: (dir: number, headsign?: string | null) =>
			headsign ? `Direction ${dir} · ${headsign}` : `Direction ${dir}`,
		sortLabel: 'Trier',
		sortDefault: 'Ordre du parcours',
		sortWorst: 'Moins fiables',
		rankingPending: 'Calcul du classement de fiabilité des arrêts filtrés…',
		inventory: {
			label: 'Inventaire du réseau',
			stops: 'Arrêts',
			bus: 'Bus',
			metro: 'Métro',
			lines: 'Lignes',
			unavailable: 'Indisponible',
		},
		browse: {
			heading: 'Parcourir les arrêts par ligne',
			lede: 'Choisissez une ligne pour voir tous ses arrêts publiés, regroupés par direction.',
			chooseLine: (short: string, long?: string | null) =>
				`Voir les arrêts de la ligne ${short}${long ? ` ${long}` : ''}`,
			showMoreLines: (n: number) => `Afficher ${n} autres lignes`,
			progressLabel: 'Progression du catalogue des arrêts',
			progress: (shown: number, total: number) => `${shown} arrêts sur ${total} affichés`,
			loadMore: (n: number) => `Afficher ${n} autres arrêts`,
		},
	},
	en: {
		kicker: 'STOPS · CATALOGUE',
		heading: 'Stops',
		subheading: '// SEARCH',
		lede: 'Search a stop by name or code to see its next departures and reliability. We never invent data.',
		searchPlaceholder: 'Stop name or code…',
		searchLabel: 'Search stops',
		noMatches: 'No stops match this search.',
		more: (n) => `+${n} more stops, refine the search`,
		mapAction: 'Map',
		viewStopOnMap: (stop) => `View stop ${stop} on map`,
		controlsLabel: 'Filters',
		lineLabel: 'Filter by line',
		linePlaceholder: 'Line number or name…',
		lineClear: 'Clear line filter',
		lineEmpty: 'No lines match.',
		onLineHeading: (short) => `Stops on line ${short}`,
		noLineStops: 'No published stop list for this line.',
		direction: (dir, headsign) =>
			headsign ? `Direction ${dir} · ${headsign}` : `Direction ${dir}`,
		sortLabel: 'Sort',
		sortDefault: 'Route order',
		sortWorst: 'Least reliable',
		rankingPending: 'Calculating reliability ranking for the filtered stops…',
		inventory: {
			label: 'Network inventory',
			stops: 'Stops',
			bus: 'Bus',
			metro: 'Metro',
			lines: 'Lines',
			unavailable: 'Not available',
		},
		browse: {
			heading: 'Browse stops by line',
			lede: 'Choose a line to see every published stop, grouped by direction.',
			chooseLine: (short, long) => `Browse stops on line ${short}${long ? ` ${long}` : ''}`,
			showMoreLines: (n) => `Show ${n} more lines`,
			progressLabel: 'Stop catalogue progress',
			progress: (shown, total) => `Showing ${shown} of ${total} stops`,
			loadMore: (n) => `Load ${n} more stops`,
		},
	},
}) satisfies Readonly<Record<Locale, SurfaceHeadCopy>>;

export type StopsIndexCopy = (typeof indexCopy)[Locale];

export const detailCopy = defineCopy({
	fr: {
		kicker: 'ARRÊT',
		back: '← Retour aux arrêts',
		article: {
			watermark: 'Arrêt',
			tagsAria: 'Données d’identité de l’arrêt',
			stopId: 'ID arrêt',
			provider: 'Fournisseur',
			updated: 'Mis à jour',
		},
		viewOnMap: 'Voir sur la carte',
		viewStopOnMap: (stop: string) => `Voir l’arrêt ${stop} sur la carte`,
		tabs: { detail: 'Détail', schedule: 'Horaire', reliability: 'Fiabilité' },
		detailCard: {
			title: 'Informations sur l’arrêt',
			summary: 'Position, accessibilité, lignes desservies et avis de service actifs.',
		},
		next: {
			terminal: { title: 'passages-en-direct', tag: 'EN DIRECT' },
			heading: 'Prochains passages',
			none: 'Aucun passage à venir pour le moment.',
			late: (min: number) => `+${min} min de retard`,
			early: (min: number) => `${Math.abs(min)} min d’avance`,
			onTime: 'à l’heure',
			noDelay: 'Temps réel indisponible',
			route: 'Ligne',
			table: {
				caption: 'Prochains passages en direct',
				route: 'Ligne',
				departure: 'Passage',
				status: 'État',
			},
			controlsLabel: 'Filtres',
			filter: {
				statusLabel: 'Filtrer par statut',
				onTime: 'À l’heure',
				late: 'En retard',
				early: 'En avance',
				routeLabel: 'Filtrer par ligne',
				allRoutes: 'Toutes les lignes',
				noMatches: 'Aucun passage ne correspond à ce filtre.',
				showing: (shown: number, total: number) => `${shown} sur ${total} passages affichés`,
			},
		},
		alerts: {
			heading: 'Avis de service',
			listLabel: 'Avis de service touchant cet arrêt',
			cause: 'Cause',
			effect: 'Effet',
			from: 'À partir de',
			until: 'Jusqu’à',
			severity: { critical: 'Critique', high: 'Élevé', watch: 'À surveiller' },
			more: (n) => `+${n} de plus`,
			showLess: 'Réduire',
		} satisfies AffectedAlertsCopy,
		info: {
			position: 'Position',
			code: 'Code d’arrêt',
			wheelchair: 'Accessibilité',
			wheelchairYes: 'Accessible en fauteuil roulant',
			wheelchairNo: 'Non accessible en fauteuil roulant',
			routesServed: 'Lignes desservies',
		},
		schedule: {
			heading: 'Horaire prévu',
			none: 'Aucun horaire prévu pour cet arrêt.',
			table: {
				caption: 'Horaire prévu par ligne',
				route: 'Ligne',
				destination: 'Destination',
				departures: 'Passages',
			},
			moreTimes: (n: number) => `+${n} autres passages`,
		},
	},
	en: {
		kicker: 'STOP',
		back: '← Back to stops',
		article: {
			watermark: 'Stop',
			tagsAria: 'Stop identity data',
			stopId: 'Stop ID',
			provider: 'Provider',
			updated: 'Updated',
		},
		viewOnMap: 'View on map',
		viewStopOnMap: (stop) => `View stop ${stop} on map`,
		tabs: { detail: 'Detail', schedule: 'Schedule', reliability: 'Reliability' },
		detailCard: {
			title: 'Stop information',
			summary: 'Position, accessibility, routes served and active service alerts.',
		},
		next: {
			terminal: { title: 'live-departures', tag: 'LIVE' },
			heading: 'Next departures',
			none: 'No upcoming departures right now.',
			late: (min) => `+${min} min late`,
			early: (min) => `${Math.abs(min)} min early`,
			onTime: 'on time',
			noDelay: 'Realtime unavailable',
			route: 'Line',
			table: {
				caption: 'Live next departures',
				route: 'Line',
				departure: 'Departure',
				status: 'Status',
			},
			controlsLabel: 'Filters',
			filter: {
				statusLabel: 'Filter by status',
				onTime: 'On time',
				late: 'Late',
				early: 'Early',
				routeLabel: 'Filter by line',
				allRoutes: 'All lines',
				noMatches: 'No departures match this filter.',
				showing: (shown, total) => `Showing ${shown} of ${total} departures`,
			},
		},
		alerts: {
			heading: 'Service alerts',
			listLabel: 'Service alerts affecting this stop',
			cause: 'Cause',
			effect: 'Effect',
			from: 'From',
			until: 'Until',
			severity: { critical: 'Critical', high: 'High', watch: 'Watch' },
			more: (n) => `+${n} more`,
			showLess: 'Show less',
		} satisfies AffectedAlertsCopy,
		info: {
			position: 'Position',
			code: 'Stop code',
			wheelchair: 'Accessibility',
			wheelchairYes: 'Wheelchair accessible',
			wheelchairNo: 'Not wheelchair accessible',
			routesServed: 'Routes served',
		},
		schedule: {
			heading: 'Scheduled service',
			none: 'No scheduled service for this stop.',
			table: {
				caption: 'Scheduled service by line',
				route: 'Line',
				destination: 'Destination',
				departures: 'Departures',
			},
			moreTimes: (n) => `+${n} more times`,
		},
	},
});

export type StopDetailCopy = (typeof detailCopy)[Locale];
