// stops.copy.ts — co-located bilingual copy for the Stops surface (slice-9.3).
//
// All user-facing strings the StopsIndex + StopDetail screens render live here,
// keyed by Locale, so the .svelte files carry zero inline copy. Domain-intrinsic
// labels (OTP / delay / "LIVE" / tab vocabulary inside the spine primitives)
// already live in those primitives and are NOT duplicated here.

import { defineCopy, type Locale } from '$lib/i18n/copy';
import type { AffectedAlertsCopy, SurfaceHeadCopy } from '$lib/components/surface';
import { articleCopy } from '$lib/components/layout/articleCopy';

export const indexCopy = defineCopy({
	fr: {
		kicker: 'ARRÊTS · CATALOGUE',
		heading: 'Arrêts',
		subheading: '// RECHERCHE',
		lede: 'Cherchez un arrêt par nom ou par code pour voir ses prochains passages et sa fiabilité. On n’invente jamais de données.',
		searchPlaceholder: 'Nom ou code d’arrêt…',
		searchLabel: 'Rechercher un arrêt',
		noMatches: 'Aucun arrêt ne correspond à cette recherche.',
		more: (n: number) => `+${n} autres arrêts, affinez la recherche`,
		mapAction: 'Carte',
		viewStopOnMap: (stop: string) => `Voir l’arrêt ${stop} sur la carte`,
		controlsLabel: 'Filtres',
		lineLabel: 'Filtrer par ligne',
		linePlaceholder: 'Numéro ou nom de ligne…',
		lineClear: 'Effacer le filtre de ligne',
		lineEmpty: 'Aucune ligne ne correspond.',
		onLineHeading: (short: string) => `Arrêts de la ligne ${short}`,
		noLineStops: 'Aucune liste d’arrêts publiée pour cette ligne.',
		direction: (dir: number, headsign?: string | null) =>
			headsign ? `Direction ${dir} · ${headsign}` : `Direction ${dir}`,
		sortLabel: 'Trier',
		sortDefault: 'Ordre du parcours',
		sortWorst: 'Moins fiables',
		rankingPending: 'Calcul du classement de fiabilité des arrêts filtrés…',
		inventory: {
			label: 'Inventaire du réseau',
			stops: 'Arrêts',
			bus: 'Bus',
			metro: 'Métro',
			lines: 'Lignes',
			unavailable: 'Indisponible',
		},
		browse: {
			heading: 'Parcourir les arrêts par ligne',
			lede: 'Choisissez une ligne pour voir tous ses arrêts publiés, regroupés par direction.',
			chooseLine: (short: string, long?: string | null) =>
				`Voir les arrêts de la ligne ${short}${long ? ` ${long}` : ''}`,
			showMoreLines: (n: number) => `Afficher ${n} autres lignes`,
			progressLabel: 'Progression du catalogue des arrêts',
			progress: (shown: number, total: number) => `${shown} arrêts sur ${total} affichés`,
			loadMore: (n: number) => `Afficher ${n} autres arrêts`,
		},
	},
	en: {
		kicker: 'STOPS · CATALOGUE',
		heading: 'Stops',
		subheading: '// SEARCH',
		lede: 'Search a stop by name or code to see its next departures and reliability. We never invent data.',
		searchPlaceholder: 'Stop name or code…',
		searchLabel: 'Search stops',
		noMatches: 'No stops match this search.',
		more: (n) => `+${n} more stops, refine the search`,
		mapAction: 'Map',
		viewStopOnMap: (stop) => `View stop ${stop} on map`,
		controlsLabel: 'Filters',
		lineLabel: 'Filter by line',
		linePlaceholder: 'Line number or name…',
		lineClear: 'Clear line filter',
		lineEmpty: 'No lines match.',
		onLineHeading: (short) => `Stops on line ${short}`,
		noLineStops: 'No published stop list for this line.',
		direction: (dir, headsign) =>
			headsign ? `Direction ${dir} · ${headsign}` : `Direction ${dir}`,
		sortLabel: 'Sort',
		sortDefault: 'Route order',
		sortWorst: 'Least reliable',
		rankingPending: 'Calculating reliability ranking for the filtered stops…',
		inventory: {
			label: 'Network inventory',
			stops: 'Stops',
			bus: 'Bus',
			metro: 'Metro',
			lines: 'Lines',
			unavailable: 'Not available',
		},
		browse: {
			heading: 'Browse stops by line',
			lede: 'Choose a line to see every published stop, grouped by direction.',
			chooseLine: (short, long) => `Browse stops on line ${short}${long ? ` ${long}` : ''}`,
			showMoreLines: (n) => `Show ${n} more lines`,
			progressLabel: 'Stop catalogue progress',
			progress: (shown, total) => `Showing ${shown} of ${total} stops`,
			loadMore: (n) => `Load ${n} more stops`,
		},
	},
}) satisfies Readonly<Record<Locale, SurfaceHeadCopy>>;

export type StopsIndexCopy = (typeof indexCopy)[Locale];

export const detailCopy = defineCopy({
	fr: {
		kicker: 'ARRÊT',
		back: '← Retour aux arrêts',
		article: articleCopy(
			'fr',
			{
				watermark: 'Arrêt',
				stopId: 'ID arrêt',
				provider: 'Fournisseur',
				updated: 'Infos d’arrêt mises à jour',
			},
			{ back: false, tagsAria: 'Données d’identité de l’arrêt' },
		),
		report: {
			departures: 'Rapport des passages',
			alerts: 'Rapport des avis',
			historic: 'Rapport de fiabilité',
			refreshUnavailable: 'Actualisation indisponible',
			behind: 'Rapport en retard',
			retained: 'Le dernier rapport reçu reste affiché. Il peut ne plus être à jour.',
			staticRefreshUnavailable: 'Informations de l’arrêt non actualisées',
			retainedStatic: 'Les dernières informations reçues restent affichées.',
			historicRefreshUnavailable: 'Fiabilité non actualisée',
			retainedHistoric: 'Le dernier rapport de fiabilité reçu reste affiché.',
		},
		summary: {
			reported: 'Résumé quotidien du rapport',
			day: (date: string) => `Observations du ${date}`,
		},
		alertState: {
			none: 'Aucun avis correspondant à cet arrêt dans ce rapport.',
			limited:
				'Les informations de l’arrêt sont indisponibles. Seuls les avis visant directement son identifiant sont affichés.',
		},
		viewOnMap: 'Voir sur la carte',
		viewStopOnMap: (stop: string) => `Voir l’arrêt ${stop} sur la carte`,
		tabs: { detail: 'Détail', schedule: 'Horaire', reliability: 'Fiabilité' },
		detailCard: {
			title: 'Informations sur l’arrêt',
			summary: 'Position, accessibilité, lignes desservies et avis de service actifs.',
		},
		next: {
			terminal: { title: 'passages-en-direct', tag: 'EN DIRECT' },
			heading: 'Prochains passages',
			none: 'Aucun passage communiqué pour cet arrêt dans ce rapport.',
			scope: 'Le rapport contient au plus deux prédictions par ligne. Elles peuvent changer.',
			late: (min: number) => `+${min} min de retard`,
			early: (min: number) => `${Math.abs(min)} min d’avance`,
			onTime: 'à l’heure',
			route: 'Ligne',
			table: {
				caption: 'Passages communiqués',
				route: 'Ligne',
				departure: 'Passage',
				status: 'État',
			},
			controlsLabel: 'Filtres',
			filter: {
				statusLabel: 'Filtrer par statut',
				onTime: 'À l’heure',
				late: 'En retard',
				early: 'En avance',
				routeLabel: 'Filtrer par ligne',
				allRoutes: 'Toutes les lignes',
				noMatches: 'Aucun passage ne correspond à ce filtre.',
				showing: (shown: number, total: number) => `${shown} sur ${total} passages affichés`,
			},
		},
		alerts: {
			heading: 'Avis de service',
			listLabel: 'Avis de service touchant cet arrêt',
			cause: 'Cause',
			effect: 'Effet',
			from: 'À partir de',
			until: 'Jusqu’à',
			severity: { critical: 'Critique', high: 'Élevé', watch: 'À surveiller' },
			more: (n) => `+${n} de plus`,
			showLess: 'Réduire',
			foreignLanguage: '(en anglais seulement)',
			link: 'Détails',
			linkAria: (host: string) => `Ouvrir les détails de l’avis sur ${host} (nouvel onglet)`,
		} satisfies AffectedAlertsCopy,
		info: {
			position: 'Position',
			code: 'Code d’arrêt',
			wheelchair: 'Accessibilité',
			wheelchairYes: 'Accessible en fauteuil roulant',
			wheelchairNo: 'Non accessible en fauteuil roulant',
			routesServed: 'Lignes desservies',
		},
		schedule: {
			heading: 'Exemple d’horaire en semaine',
			none: 'Aucun exemple d’horaire publié pour cet arrêt.',
			scope:
				'Heures sélectionnées dans un horaire représentatif de semaine. Ce n’est pas l’horaire complet ni nécessairement celui d’aujourd’hui. Les heures suivent la journée de service : 25:30 signifie 01:30 le lendemain.',
			table: {
				caption: 'Exemples d’heures en semaine par ligne',
				route: 'Ligne',
				destination: 'Destination',
				departures: 'Passages',
			},
			moreTimes: (n: number) => `+${n} autres heures publiées`,
		},
	},
	en: {
		kicker: 'STOP',
		back: '← Back to stops',
		article: articleCopy(
			'en',
			{
				watermark: 'Stop',
				stopId: 'Stop ID',
				provider: 'Provider',
				updated: 'Stop info updated',
			},
			{ back: false, tagsAria: 'Stop identity data' },
		),
		report: {
			departures: 'Departure report',
			alerts: 'Alert report',
			historic: 'Reliability report',
			refreshUnavailable: 'Refresh unavailable',
			behind: 'Report behind schedule',
			retained: 'Showing the last report received. It may no longer be current.',
			staticRefreshUnavailable: 'Stop information could not refresh',
			retainedStatic: 'Showing the last stop information received.',
			historicRefreshUnavailable: 'Reliability could not refresh',
			retainedHistoric: 'Showing the last reliability report received.',
		},
		summary: { reported: 'Reported daily summary', day: (date) => `Observations on ${date}` },
		alertState: {
			none: 'No matching alerts for this stop in this report.',
			limited:
				'Stop information is unavailable. Only alerts targeting this stop ID directly are shown.',
		},
		viewOnMap: 'View on map',
		viewStopOnMap: (stop) => `View stop ${stop} on map`,
		tabs: { detail: 'Detail', schedule: 'Schedule', reliability: 'Reliability' },
		detailCard: {
			title: 'Stop information',
			summary: 'Position, accessibility, routes served and active service alerts.',
		},
		next: {
			terminal: { title: 'live-departures', tag: 'LIVE' },
			heading: 'Next departures',
			none: 'No departures reported for this stop in this report.',
			scope: 'The report includes up to two predictions per line. They may change.',
			late: (min) => `+${min} min late`,
			early: (min) => `${Math.abs(min)} min early`,
			onTime: 'on time',
			route: 'Line',
			table: {
				caption: 'Reported departures',
				route: 'Line',
				departure: 'Departure',
				status: 'Status',
			},
			controlsLabel: 'Filters',
			filter: {
				statusLabel: 'Filter by status',
				onTime: 'On time',
				late: 'Late',
				early: 'Early',
				routeLabel: 'Filter by line',
				allRoutes: 'All lines',
				noMatches: 'No departures match this filter.',
				showing: (shown, total) => `Showing ${shown} of ${total} departures`,
			},
		},
		alerts: {
			heading: 'Service alerts',
			listLabel: 'Service alerts affecting this stop',
			cause: 'Cause',
			effect: 'Effect',
			from: 'From',
			until: 'Until',
			severity: { critical: 'Critical', high: 'High', watch: 'Watch' },
			more: (n) => `+${n} more`,
			showLess: 'Show less',
			foreignLanguage: '(French only)',
			link: 'Details',
			linkAria: (host) => `Open the alert details on ${host} (new tab)`,
		} satisfies AffectedAlertsCopy,
		info: {
			position: 'Position',
			code: 'Stop code',
			wheelchair: 'Accessibility',
			wheelchairYes: 'Wheelchair accessible',
			wheelchairNo: 'Not wheelchair accessible',
			routesServed: 'Routes served',
		},
		schedule: {
			heading: 'Sample weekday schedule',
			none: 'No sample schedule published for this stop.',
			scope:
				'Selected times from a representative weekday schedule. This is not the complete timetable or necessarily today’s service. Times follow the service day: 25:30 means 01:30 the next day.',
			table: {
				caption: 'Sample weekday times by line',
				route: 'Line',
				destination: 'Destination',
				departures: 'Departures',
			},
			moreTimes: (n) => `+${n} more times`,
		},
	},
});

export type StopDetailCopy = (typeof detailCopy)[Locale];
