name = "transit-data-proxy"
main = "src/worker.js"
compatibility_date = "2026-06-10"
account_id = "eccfb9bedd87d413eaf4cac6ae2285d3"
workers_dev = false

routes = [
  { pattern = "transit.yesid.dev/data/*", zone_name = "yesid.dev" },
  { pattern = "transit.yesid.dev/api/v1/*", zone_name = "yesid.dev" },
]

[[r2_buckets]]
binding = "SNAPSHOTS"
bucket_name = "transit-snapshots"
